#!/usr/bin/env python3
# rename files to lowercase, replacing spaces with underscores
from pathlib import Path
from sys import argv


def main():
    
    goodset = set('abcdefghijklmnopqrstuvwyxz0123456789:._-')

    for arg in argv[1:]:
        p = Path(arg).absolute()
        p.rename(p.parent / ''.join(c for c in p.name.lower().replace(' ', '_') if c in goodset))


if __name__ == "__main__":
    main()


